formulario crear productos desde admin corregido y reemplazo de alert…
Henry-Proyecto-Firnal-P-10b/vite-front-PF pull request #139
Opened 2023-05-15 20:51 UTC by BiancaStork

error en create products corregido!

2023-05-16 16:11 UTC, JohnRSantamaria approved these changes
Verificado, buen trabajo

2023-05-16 16:53 UTC, JohnRSantamaria requested changes
Hay un problema al leer las categorias

2023-05-17 03:46 UTC, BiancaStork commented
volvi a hacer pull con los cambios...
ahora funciona todo y agregue renderizacion de las categorias seleccionadas y opcion de eliminar en create
y al formulario de edit todavia le faltan funcionalidades

2023-05-17 14:43 UTC, JohnRSantamaria approved these changes
Error corregido, buen trabajo

2023-05-17 14:43 UTC, merged